"""postgres_primary

Revision ID: 0001
Revises:
Create Date: 2026-07-10 22:38:02.411041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA plk_memory")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('human', 'agent', 'service')",
            name=op.f("ck_audit_events_actor_type"),
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "audit_id", name=op.f("pk_audit_events")
        ),
        schema="plk_memory",
    )
    op.create_index(
        "ix_audit_events_org_resource_created",
        "audit_events",
        ["organization_id", "resource_type", "resource_id", "created_at"],
        unique=False,
        schema="plk_memory",
    )
    op.create_table(
        "idempotency_records",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column(
            "response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "organization_id", "idempotency_key", name=op.f("pk_idempotency_records")
        ),
        schema="plk_memory",
    )
    op.create_table(
        "knowledge_facts",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("current_revision_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('philosophy', 'logic', 'knowhow')",
            name=op.f("ck_knowledge_facts_fact_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'invalidated')",
            name=op.f("ck_knowledge_facts_fact_status"),
        ),
        sa.CheckConstraint(
            "current_version >= 1", name=op.f("ck_knowledge_facts_positive_version")
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "fact_id", name=op.f("pk_knowledge_facts")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "current_revision_id",
            name="uq_knowledge_facts_org_current_revision",
        ),
        schema="plk_memory",
    )
    op.create_index(
        "ix_knowledge_facts_org_namespace_status",
        "knowledge_facts",
        ["organization_id", "namespace", "status"],
        unique=False,
        schema="plk_memory",
    )
    op.create_table(
        "outbox_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=255), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "aggregate_version >= 1",
            name=op.f("ck_outbox_events_positive_aggregate_version"),
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_outbox_events_nonnegative_attempts")
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "event_id", name=op.f("pk_outbox_events")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "aggregate_type",
            "aggregate_id",
            "aggregate_version",
            "event_type",
            name="uq_outbox_events_org_aggregate_version_type",
        ),
        schema="plk_memory",
    )
    op.create_index(
        "ix_outbox_events_claimable",
        "outbox_events",
        ["available_at", "occurred_at"],
        unique=False,
        schema="plk_memory",
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.create_table(
        "knowledge_fact_revisions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("revision_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("why", sa.Text(), nullable=False),
        sa.Column("how_to_apply", sa.Text(), nullable=False),
        sa.Column(
            "sources",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("invalidation_reason", sa.Text(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('human', 'agent', 'service')",
            name=op.f("ck_knowledge_fact_revisions_actor_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(sources) = 'array'",
            name=op.f("ck_knowledge_fact_revisions_sources_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(tags) = 'array'",
            name=op.f("ck_knowledge_fact_revisions_tags_array"),
        ),
        sa.CheckConstraint(
            "kind IN ('philosophy', 'logic', 'knowhow')",
            name=op.f("ck_knowledge_fact_revisions_fact_kind"),
        ),
        sa.CheckConstraint(
            "source_type IN ('user', 'agent', 'external-untrusted')",
            name=op.f("ck_knowledge_fact_revisions_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'invalidated')",
            name=op.f("ck_knowledge_fact_revisions_fact_status"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_knowledge_fact_revisions_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "fact_id"],
            [
                "plk_memory.knowledge_facts.organization_id",
                "plk_memory.knowledge_facts.fact_id",
            ],
            name="fk_knowledge_fact_revisions_org_fact",
            ondelete="CASCADE",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "revision_id", name=op.f("pk_knowledge_fact_revisions")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "fact_id",
            "version",
            name="uq_knowledge_fact_revisions_org_fact_version",
        ),
        schema="plk_memory",
    )
    op.create_index(
        "ix_knowledge_fact_revisions_org_fact_created",
        "knowledge_fact_revisions",
        ["organization_id", "fact_id", "created_at"],
        unique=False,
        schema="plk_memory",
    )
    op.create_foreign_key(
        "fk_knowledge_facts_org_current_revision",
        "knowledge_facts",
        "knowledge_fact_revisions",
        ["organization_id", "current_revision_id"],
        ["organization_id", "revision_id"],
        source_schema="plk_memory",
        referent_schema="plk_memory",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_table(
        "search_projection_state",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("backend", sa.String(length=64), nullable=False),
        sa.Column("fact_id", sa.String(length=64), nullable=False),
        sa.Column("indexed_version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "backend_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_event_id", sa.UUID(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(backend_refs) = 'array'",
            name=op.f("ck_search_projection_state_backend_refs_array"),
        ),
        sa.CheckConstraint(
            "indexed_version >= 1",
            name=op.f("ck_search_projection_state_positive_indexed_version"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "fact_id"],
            [
                "plk_memory.knowledge_facts.organization_id",
                "plk_memory.knowledge_facts.fact_id",
            ],
            name="fk_search_projection_state_org_fact",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id",
            "backend",
            "fact_id",
            name=op.f("pk_search_projection_state"),
        ),
        schema="plk_memory",
    )
    op.create_table(
        "approval_requests",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="pending", nullable=False
        ),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("request_reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'stale', 'cancelled')",
            name=op.f("ck_approval_requests_approval_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "fact_id", "source_version"],
            [
                "plk_memory.knowledge_fact_revisions.organization_id",
                "plk_memory.knowledge_fact_revisions.fact_id",
                "plk_memory.knowledge_fact_revisions.version",
            ],
            name="fk_approval_requests_org_fact_version",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "request_id", name=op.f("pk_approval_requests")
        ),
        schema="plk_memory",
    )
    op.create_index(
        "ix_approval_requests_org_status_created",
        "approval_requests",
        ["organization_id", "status", "created_at"],
        unique=False,
        schema="plk_memory",
    )
    op.create_table(
        "knowledge_relations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("relation_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.String(length=32), nullable=False),
        sa.Column("from_fact_id", sa.String(length=64), nullable=False),
        sa.Column("to_fact_id", sa.String(length=64), nullable=False),
        sa.Column("created_revision_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation_type IN ('supersedes', 'related_to')",
            name=op.f("ck_knowledge_relations_relation_type"),
        ),
        sa.CheckConstraint(
            "from_fact_id <> to_fact_id",
            name=op.f("ck_knowledge_relations_different_facts"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_revision_id"],
            [
                "plk_memory.knowledge_fact_revisions.organization_id",
                "plk_memory.knowledge_fact_revisions.revision_id",
            ],
            name="fk_knowledge_relations_org_created_revision",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "from_fact_id"],
            [
                "plk_memory.knowledge_facts.organization_id",
                "plk_memory.knowledge_facts.fact_id",
            ],
            name="fk_knowledge_relations_org_from_fact",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "to_fact_id"],
            [
                "plk_memory.knowledge_facts.organization_id",
                "plk_memory.knowledge_facts.fact_id",
            ],
            name="fk_knowledge_relations_org_to_fact",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "relation_id", name=op.f("pk_knowledge_relations")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "relation_type",
            "from_fact_id",
            "to_fact_id",
            name="uq_knowledge_relations_org_type_from_to",
        ),
        schema="plk_memory",
    )
    op.create_index(
        "uq_knowledge_relations_one_active_superseder",
        "knowledge_relations",
        ["organization_id", "to_fact_id"],
        unique=True,
        schema="plk_memory",
        postgresql_where=sa.text("relation_type = 'supersedes' AND is_active"),
    )
    op.create_table(
        "approval_decisions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('human', 'agent', 'service')",
            name=op.f("ck_approval_decisions_actor_type"),
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')",
            name=op.f("ck_approval_decisions_approval_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "request_id"],
            [
                "plk_memory.approval_requests.organization_id",
                "plk_memory.approval_requests.request_id",
            ],
            name="fk_approval_decisions_org_request",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "decision_id", name=op.f("pk_approval_decisions")
        ),
        sa.UniqueConstraint(
            "organization_id", "request_id", name="uq_approval_decisions_org_request"
        ),
        schema="plk_memory",
    )
    op.execute(
        """
        CREATE FUNCTION plk_memory.reject_immutable_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only', TG_TABLE_NAME
                USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$
        """
    )
    for immutable_table in ("knowledge_fact_revisions", "audit_events"):
        op.execute(
            f"CREATE TRIGGER reject_mutation BEFORE UPDATE OR DELETE "
            f"ON plk_memory.{immutable_table} FOR EACH ROW "
            "EXECUTE FUNCTION plk_memory.reject_immutable_mutation()"
        )
    tenant_expression = (
        "organization_id = "
        "NULLIF(current_setting('app.current_organization_id', true), '')::uuid"
    )
    tenant_tables = (
        "knowledge_facts",
        "knowledge_fact_revisions",
        "knowledge_relations",
        "idempotency_records",
        "outbox_events",
        "approval_requests",
        "approval_decisions",
        "search_projection_state",
        "audit_events",
    )
    for table_name in tenant_tables:
        op.execute(f"ALTER TABLE plk_memory.{table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY organization_isolation ON plk_memory.{table_name} "
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("approval_decisions", schema="plk_memory")
    op.drop_index(
        "uq_knowledge_relations_one_active_superseder",
        table_name="knowledge_relations",
        schema="plk_memory",
        postgresql_where=sa.text("relation_type = 'supersedes' AND is_active"),
    )
    op.drop_table("knowledge_relations", schema="plk_memory")
    op.drop_index(
        "ix_approval_requests_org_status_created",
        table_name="approval_requests",
        schema="plk_memory",
    )
    op.drop_table("approval_requests", schema="plk_memory")
    op.drop_table("search_projection_state", schema="plk_memory")
    op.drop_constraint(
        "fk_knowledge_facts_org_current_revision",
        "knowledge_facts",
        schema="plk_memory",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_knowledge_fact_revisions_org_fact_created",
        table_name="knowledge_fact_revisions",
        schema="plk_memory",
    )
    op.drop_table("knowledge_fact_revisions", schema="plk_memory")
    op.drop_index(
        "ix_outbox_events_claimable",
        table_name="outbox_events",
        schema="plk_memory",
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.drop_table("outbox_events", schema="plk_memory")
    op.drop_index(
        "ix_knowledge_facts_org_namespace_status",
        table_name="knowledge_facts",
        schema="plk_memory",
    )
    op.drop_table("knowledge_facts", schema="plk_memory")
    op.drop_table("idempotency_records", schema="plk_memory")
    op.drop_index(
        "ix_audit_events_org_resource_created",
        table_name="audit_events",
        schema="plk_memory",
    )
    op.drop_table("audit_events", schema="plk_memory")
    op.execute("DROP FUNCTION plk_memory.reject_immutable_mutation()")
    op.execute("DROP SCHEMA plk_memory")
    # ### end Alembic commands ###
